apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: team-navno-alerts
  namespace: personbruker
  labels:
    alertmanagerConfig: team-navno-alerts
    team: personbruker
spec:
  receivers:
    - name: team-navno-default-alerts
    - name: team-navno-frontend-alerts
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-navno-frontend-alerts'
          iconEmoji: ':meow_oopskeyboard:'
          username: 'Testing alert frontend'
          sendResolved: true
          title: '{{ template "slack.title" . }}'
          text: '{{ template "slack.text" . }}'
          color: '{{ template "slack.color" . }}'
    - name: team-navno-backend-alerts
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-navno-backend-alerts'
          iconEmoji: ':meow_oopskeyboard:'
          username: 'Testing Alert backend'
          sendResolved: true
          title: '{{ template "slack.title" . }}'
          text: '{{ template "slack.text" . }}'
          color: '{{ template "slack.color" . }}'
  route:
    groupInterval: 1m
    groupWait: 10s
    repeatInterval: 15m
    receiver: "team-navno-default-alerts"
    routes:
      - receiver: "team-navno-frontend-alerts"
        matchers:
          - name: "receiver_reference"
            matchType: "="
            value: "team-navno-frontend-alerts"
      - receiver: "team-navno-backend-alerts"
        matchers:
          - name: "receiver_reference"
            matchType: "="
            value: "team-navno-backend-alerts"